version: "2.2"

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:20.0.0
    container_name: keycloak_web
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhostcert.pem
#      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhostkey.pem
      # KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KC_HOSTNAME_URL: http://localhost:8080
    depends_on:
      keycloakdb:
        condition: service_healthy
    ports:
      - '8080:8080'
#      - '8843:8443'
#    volumes:
#      - ./certs:/opt/keycloak/certs
    networks:
      - keycloak_network

  keycloakdb:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_network

  # keycloak_nginx:
  #   build: ./nginx
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   depends_on:
  #     - keycloak_web
  #   networks:
  #     - keycloak_network

volumes:
  postgres_data:
    driver: local
networks:
  keycloak_network:
    driver: bridge





